name: ci
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"
          cache: true

      - name: ci/vet
        run: go vet ./...

      - name: ci/test
        run: go test -v -race ./...
